# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c

# header files
INCLUDES=

# the name of this project
PROJECT=filetest


# the makefile is useless without the next line!
include ../../include/common.mk
