# Makefile for a cc3 project


# C files to compile
CSOURCES=scripter.c slip.c csmsg.c lualib.c

# header files
INCLUDES=slip.h scripter.h csmsg.h lualib.h

# library files
LIBS = lua51 jpeg-6b cc3-ilp

# the name of this project
PROJECT=camscripter


# the makefile is useless without the next line!
include ../../include/common.mk
