# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c

# header files
INCLUDES=

# header files
LIBS=

# the name of this project
PROJECT=led-test


# the makefile is useless without the next line!
include ../../include/common.mk
