LIB = cc3_ilp
LIBS += jpeg-6b

CSOURCES = cc3_ilp.c cc3_color_track.c cc3_color_info.c cc3_jpg.c

INCLUDES = cc3_ilp.h cc3_color_track.h cc3_color_info.h cc3_jpg.h




include ../../include/common.mk
