# Makefile for a cc3 project

# C files to compile
CSOURCES=main.c

# header files
INCLUDES=

# header files
LIBS=cc3-ilp jpeg-6b

# the name of this project
PROJECT=security-cam


# the makefile is useless without the next line!
include ../../include/common.mk
