# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c hash_32.c

# header files
INCLUDES=fnv.h

# header files
LIBS=

# the name of this project
PROJECT=serial-test


# the makefile is useless without the next line!
include ../../include/common.mk
