LIB = libpng-12

CSOURCES = png.c pngerror.c pngget.c pngmem.c pngpread.c \
	pngread.c pngrio.c pngrtran.c pngrutil.c pngset.c \
	pngtrans.c pngwio.c pngwrite.c pngwtran.c pngwutil.c

INCLUDES = png.h pngconf.h

LIBS += zlib



include ../../include/common.mk
