# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c polly.c

# header files
INCLUDES=polly.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=polly


# the makefile is useless without the next line!
include ../../include/common.mk
