LIB = lua51

CSOURCES = lapi.c      ldo.c    lgc.c     llex.c      loadlib.c \
	   loslib.c   lstring.c  ltablib.c  lzio.c \
	   lauxlib.c   ldblib.c  ldump.c  linit.c   lmathlib.c  lobject.c  \
	   lparser.c  lstrlib.c  ltm.c      lundump.c  print.c \
	   lbaselib.c  ldebug.c  lfunc.c  liolib.c  lmem.c      lopcodes.c \
           lstate.c   ltable.c   lvm.c 


INCLUDES = lapi.h     ldebug.h  lgc.h      lmem.h      lparser.h  ltable.h \
	   lua.h      lvm.h lauxlib.h  ldo.h     llex.h     lobject.h  \
	   lstate.h   ltm.h      lualib.h   lzio.h \
	   lfunc.h   llimits.h  lopcodes.h  lstring.h  \
	   luaconf.h  lundump.h 





include ../../include/common.mk
