LIB = cc3-ilp
LIBS += jpeg-6b

CSOURCES = cc3_ilp.c cc3_color_track.c cc3_color_info.c cc3_jpg.c cc3_math.c cc3_conv.c cc3_connected_component.c cc3_img_writer.c cc3_histogram.c cc3_frame_diff.c cc3_hsv.c

INCLUDES = cc3_ilp.h cc3_color_track.h cc3_color_info.h cc3_jpg.h cc3_math.h cc3_conv.h cc3_connected_component.h cc3_img_writer.h cc3_histogram.h cc3_frame_diff.h cc3_hsv.h




include ../../include/common.mk
