# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c LPC2k_ee.c

# header files
INCLUDES=LPC2k_ee.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=eeprom-test


# Thumb mode
#
# if you are building against an ARM hal (like lpc2106-cmucam3), then
# uncomment the next line if you want to build smaller (but possibly
# slower code)

#thumb=1


# hal selection
#
# if you want to build against a non-default hal (other than lpc2106-cmucam3), 
# then uncomment the next line and specify the hal you want

#hal=


# the makefile is useless without the next line!
include ../../include/common.mk
