# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c LPC2k_ee.c

# header files
INCLUDES=LPC2k_ee.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=eeprom-test


# the makefile is useless without the next line!
include ../../include/common.mk
