# Makefile for a cc3 project


# C files to compile
CSOURCES=main.c spoonBot.c

# header files
INCLUDES=spoonBot.h

# header files
LIBS=cc3-ilp

# the name of this project
PROJECT=spoonBot


# the makefile is useless without the next line!
include ../../include/common.mk
