LIB = zlib

CSOURCES = adler32.c compress.c crc32.c gzio.c uncompr.c deflate.c trees.c \
	zutil.c inflate.c infback.c inftrees.c inffast.c

INCLUDES = zlib.h zconf.h crc32.h deflate.h zutil.h inftrees.h inflate.h \
	inffast.h trees.h


include ../../include/common.mk
